Repository Namo-log/iOS_SwiftUI, pull requests merged in 2024-04, with the labels that each got.

#49 Feat: RealmManager 생성 및 스케쥴 페이징 구현
  Namo_SwiftUI/Namo_SwiftUI.xcodeproj/project.pbxproj
  Namo_SwiftUI/Namo_SwiftUI/App/NamoHome.swift
  Namo_SwiftUI/Namo_SwiftUI/Business/AppState.swift
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Schedule/ScheduleInteractor.swift
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Schedule/ScheduleInteractorImpl.swift
  Namo_SwiftUI/Namo_SwiftUI/Common/Extensions/Date+.swift
  Namo_SwiftUI/Namo_SwiftUI/Common/Extensions/List+.swift
  Namo_SwiftUI/Namo_SwiftUI/Common/Extensions/NotificationName+.swift
  Namo_SwiftUI/Namo_SwiftUI/Data/Local/RealmManager.swift
  Namo_SwiftUI/Namo_SwiftUI/Model/DTO/ScheduleDTO.swift
  Namo_SwiftUI/Namo_SwiftUI/Model/Realm/RealmSchedule.swift
  Namo_SwiftUI/Namo_SwiftUI/Model/Schedule.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeMain/HomeMainView.swift
Labels: 💡Feat

#51 Fix: 캘린더 스크롤 시 frame이 안 맞는 이슈 수정
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Group/GroupCalendarView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeMain/CalendarItem.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeMain/HomeMainView.swift
Labels: 🔧Fix

#53 Feat: 그룹 캘린더 구현
  Namo_SwiftUI/Namo_SwiftUI/Business/AppState.swift
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Moim/MoimInteractor.swift
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Moim/MoimInteractorImpl.swift
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Schedule/ScheduleInteractor.swift
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Schedule/ScheduleInteractorImpl.swift
  Namo_SwiftUI/Namo_SwiftUI/Data/API/EndPoint/Moim/MoimEndPoint.swift
  Namo_SwiftUI/Namo_SwiftUI/Model/DTO/MoimDTO.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Group/GroupCalendarView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Group/GroupMain/GroupMainView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeMain/CalendarItem.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeMain/CalendarScheduleDetailItem.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeMain/CalendarScheduleItem.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeMain/HomeMainView.swift
  Namo_SwiftUI/Namo_SwiftUI/Repository/Moim/MoimRepository.swift
  Namo_SwiftUI/Namo_SwiftUI/Repository/Moim/MoimRepositoryImpl.swift
Labels: 💡Feat

#57 [Feat] 캘린더 일정 개수 많은 경우 +숫자로 뜨도록 구현, 기타 버그 수정
  Namo_SwiftUI/Namo_SwiftUI.xcodeproj/project.pbxproj
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Moim/MoimInteractorImpl.swift
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Schedule/ScheduleInteractorImpl.swift
  Namo_SwiftUI/Namo_SwiftUI/Common/Utils/Constants.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Components/NamoAlertViewWithTitle.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Group/GroupCalendarView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Group/GroupMain/GroupMainView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeMain/CalendarItem.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeMain/CalendarScheduleDetailItem.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeMain/HomeMainView.swift
Labels: 💡Feat

#62 [Feat] 홈 화면 QA 반영
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomCustomNoSelect.imageset/Contents.json
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomCustomNoSelect.imageset/Property 1=Custom, Selected=false.svg
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomCustomNoSelect.imageset/ic_bottom_custom_no_select.png
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomCustomSelect.imageset/Contents.json
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomCustomSelect.imageset/Property 1=Custom, Selected=true.svg
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomCustomSelect.imageset/ic_bottom_custom_select.png
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomDiaryNoSelect.imageset/Contents.json
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomDiaryNoSelect.imageset/Property 1=Diary, Selected=false.svg
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomDiaryNoSelect.imageset/ic_bottom_diary_no_select 1.png
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomDiarySelect.imageset/Contents.json
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomDiarySelect.imageset/Property 1=Diary, Selected=true.svg
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomDiarySelect.imageset/ic_bottom_diary_select 1.png
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomHomeNoSelect.imageset/Contents.json
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomHomeNoSelect.imageset/Property 1=Home, Selected=false.svg
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomHomeNoSelect.imageset/ic_bottom_home_no_select.png
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomHomeSelect.imageset/Contents.json
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomHomeSelect.imageset/Property 1=Home, Selected=true.svg
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomHomeSelect.imageset/ic_bottom_home_select 1.png
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomShareNoSelect.imageset/Contents.json
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomShareNoSelect.imageset/Property 1=Group, Selected=false.svg
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomShareNoSelect.imageset/ic_bottom_share_no_select.png
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomShareSelect.imageset/Contents.json
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomShareSelect.imageset/Property 1=Group, Selected=true.svg
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomShareSelect.imageset/ic_bottom_share_select 1.png
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Schedule/ScheduleInteractorImpl.swift
  Namo_SwiftUI/Namo_SwiftUI/Common/Extensions/YearMonthDay+.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Group/GroupCalendarView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeMain/CalendarItem.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeMain/HomeMainView.swift
Labels: 🔧Fix

#66 [FIX] 카카오맵 버전 업데이트 대응
  Namo_SwiftUI/Namo_SwiftUI.xcodeproj/project.pbxproj
  Namo_SwiftUI/Namo_SwiftUI.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Components/KakaoMapView.swift
Labels: 🔧Fix

#70 [Feat] 일정 QA 반영
  Namo_SwiftUI/Namo_SwiftUI.xcodeproj/project.pbxproj
  Namo_SwiftUI/Namo_SwiftUI/Common/Extensions/UIApplication+.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Group/GroupToDo/GroupToDoEditView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeToDo/ToDoEditView.swift
Labels: 💡Feat, 🔧Fix
