Repository Namo-log/iOS_SwiftUI, pull requests merged in 2024-05, with the labels that each got.

#75 [Feat] 모임 메모 관련 기능 구현 및 기록 QA 일부 반영
  Namo_SwiftUI/Namo_SwiftUI.xcodeproj/project.pbxproj
  Namo_SwiftUI/Namo_SwiftUI.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Namo_SwiftUI/Namo_SwiftUI/Business/AppState.swift
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Diary/DiaryInteractor.swift
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Diary/DiaryInteractorImpl.swift
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Diary/MoimDiaryInteractor.swift
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Diary/MoimDiaryInteractorImpl.swift
  Namo_SwiftUI/Namo_SwiftUI/Data/API/Base/APIManager.swift
  Namo_SwiftUI/Namo_SwiftUI/Data/API/EndPoint/Diary/DiaryEndPoint.swift
  Namo_SwiftUI/Namo_SwiftUI/Data/API/EndPoint/Diary/MoimDiaryEndPoint.swift
  Namo_SwiftUI/Namo_SwiftUI/Model/DTO/DiaryDTO.swift
  Namo_SwiftUI/Namo_SwiftUI/Model/DTO/MoimDTO.swift
  Namo_SwiftUI/Namo_SwiftUI/Model/DTO/MoimDiaryDTO.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Diary/DiaryMain/DiaryMainView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Diary/DiaryMain/EditDiaryView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Diary/DiaryMain/EditMoimDiaryView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Diary/DiaryMain/MoimPlaceView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeMain/CalendarScheduleDetailItem.swift
  Namo_SwiftUI/Namo_SwiftUI/Repository/Diary/DiaryRepository.swift
  Namo_SwiftUI/Namo_SwiftUI/Repository/Diary/DiaryRepositoryImpl.swift
  Namo_SwiftUI/Namo_SwiftUI/Repository/Diary/MoimDiaryRepository.swift
  Namo_SwiftUI/Namo_SwiftUI/Repository/Diary/MoimDiaryRepositoryImpl.swift
Labels: 💡Feat

#86 [Feat] 일정 QA 2차 반영
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Place/PlaceInteractor.swift
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Place/PlaceInteractorImpl.swift
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Schedule/ScheduleInteractor.swift
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Schedule/ScheduleInteractorImpl.swift
  Namo_SwiftUI/Namo_SwiftUI/Model/DTO/ScheduleDTO.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Group/GroupCalendarView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeMain/HomeMainView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeToDo/ToDoEditView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeToDo/ToDoSelectPlaceView.swift
Labels: 💡Feat, 🔧Fix

#91 [Feat] 개인 및 모임 기록 관련 2차 QA 반영
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Diary/MoimDiaryInteractorImpl.swift
  Namo_SwiftUI/Namo_SwiftUI/Data/API/EndPoint/Diary/DiaryEndPoint.swift
  Namo_SwiftUI/Namo_SwiftUI/Model/DTO/MoimDiaryDTO.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Diary/DiaryMain/DiaryMainView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Diary/DiaryMain/EditDiaryView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Diary/DiaryMain/EditMoimDiaryView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Diary/DiaryMain/MoimPlaceView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeMain/CalendarScheduleDetailItem.swift
  Namo_SwiftUI/Namo_SwiftUI/Repository/Diary/DiaryRepositoryImpl.swift
Labels: 💡Feat, 🔧Fix

#93 [FEAT] 디자인 QA 진행
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Color/TextDisabled.colorset/Contents.json
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/ArrowBasic.imageset/ArrowBasic.png
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/ArrowBasic.imageset/Contents.json
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/ArrowBasic.imageset/Vector 1.svg
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/app_logo_square 2.imageset/Contents.json
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/app_logo_square 2.imageset/app_logo_square 2.png
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/app_logo_square 2.imageset/namo_logo_svg.svg
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/btn_add_record.imageset/Contents.json
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/btn_add_record.imageset/Record.svg
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/btn_add_record.imageset/btn_add_record.png
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/btn_add_record_orange.imageset/Contents.json
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/btn_add_record_orange.imageset/Record.svg
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/btn_add_record_orange.imageset/btn_add_record_orange.png
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/btn_copy.imageset/Contents.json
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/btn_copy.imageset/btn_copy.png
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/btn_copy.imageset/ic_duplicate.svg
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/floatingAdd.imageset/Contents.json
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/floatingAdd.imageset/floating_add_n.png
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/floatingAdd.imageset/ic_floating_add.svg
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomDiarySelect.imageset/Contents.json
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomDiarySelect.imageset/Property 1=Diary, Selected=true.svg
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/icBottomDiarySelect.imageset/Property 1=_Diary, Selected=true.svg
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/mongi 1.imageset/Contents.json
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/mongi 1.imageset/mongi 1.svg
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/mongi 1.imageset/namo-mong 1.svg
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/vector3.imageset/Contents.json
  Namo_SwiftUI/Namo_SwiftUI/Assets.xcassets/Icon/vector3.imageset/Vector 3.png
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Diary/DiaryMain/DiaryMainView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Group/GroupCalendarView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Group/GroupMain/GroupMainView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Group/GroupToDo/GroupToDoEditView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeMain/HomeMainView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeToDo/ToDoEditView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Onboarding/OnboardingMain/AgreeSubView.swift
Labels: 💡Feat

#97 [Fix] 일정 QA 3차 반영
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Group/GroupToDo/GroupToDoEditView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeToDo/ToDoEditView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeToDo/ToDoSelectPlaceView.swift
Labels: 💡Feat, 🔧Fix

#99 [Fix] 기록 관련 3차 QA
  Namo_SwiftUI/Namo_SwiftUI/App/Namo_SwiftUIApp.swift
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Diary/DiaryInteractor.swift
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Diary/DiaryInteractorImpl.swift
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Diary/MoimDiaryInteractor.swift
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Diary/MoimDiaryInteractorImpl.swift
  Namo_SwiftUI/Namo_SwiftUI/Data/API/EndPoint/Diary/MoimDiaryEndPoint.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Diary/DiaryMain/DiaryMainView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Diary/DiaryMain/EditDiaryView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Diary/DiaryMain/EditMoimDiaryView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Diary/DiaryMain/MoimPlaceView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeMain/CalendarScheduleDetailItem.swift
  Namo_SwiftUI/Namo_SwiftUI/Repository/Diary/MoimDiaryRepository.swift
  Namo_SwiftUI/Namo_SwiftUI/Repository/Diary/MoimDiaryRepositoryImpl.swift
Labels: 🔧Fix

#100 [Fix] 기록 관련 3차 QA - 2
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Diary/MoimDiaryInteractor.swift
  Namo_SwiftUI/Namo_SwiftUI/Business/Interactor/Diary/MoimDiaryInteractorImpl.swift
  Namo_SwiftUI/Namo_SwiftUI/Data/API/EndPoint/Diary/MoimDiaryEndPoint.swift
  Namo_SwiftUI/Namo_SwiftUI/Model/DTO/MoimDiaryDTO.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Diary/DiaryMain/EditDiaryView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Diary/DiaryMain/EditMoimDiaryView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Diary/DiaryMain/MoimPlaceView.swift
  Namo_SwiftUI/Namo_SwiftUI/Presentation/Home/HomeMain/CalendarScheduleDetailItem.swift
  Namo_SwiftUI/Namo_SwiftUI/Repository/Diary/MoimDiaryRepository.swift
  Namo_SwiftUI/Namo_SwiftUI/Repository/Diary/MoimDiaryRepositoryImpl.swift
Labels: 🔧Fix
